# Generated by Django 4.2 on 2023-04-22 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_publish_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 22, 12, 10, 28, 548352, tzinfo=datetime.timezone.utc)),
        ),
    ]
